version: "3.1"


services:

  backend:
    image: leesanghoon94/backend:1.0
    container_name: server
    ports:
      - "3000:3000"
      

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

    